---
title: "task2-logregression"
author: "Carmen Galaz-García"
date: "1/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning=FALSE)

library(tidyverse)
library(broom)

```



```{r}
# --- DATA SELECTION ---- 
raw_palmetto <- read_csv("palmetto.csv") %>% 
  count(year,plant)
palmetto <- raw_palmetto%>% 
  select(species, height:green_lvs) %>% 
  mutate(species = case_when( species==1 ~ "serenoa repens",
                              species==2 ~ "sabal etonia"))

palmetto$species<- as.factor(palmetto$species) # convert to factor
#levels(palmetto$species)    # check factor levels
```


```{r}
# --- GRAPH 1: CANOPY DIMENSIONS ---
ggplot(data=palmetto, aes(x=length, y=width))+
  geom_point( cex=0.3, alpha=0.2)+
  facet_wrap(~species)+
  labs( x= "length (cm)",
        y= "width (cm)")+
  theme_light()
  
```

**Fig 1.** . Relationship between widest length of the canopy (cm) and widest width of the canopy perpendicular to the canopy length (cm) of the palmetto plant species *sabal etonia* and *serenoa repens*. Each point indicates measurements of an individual plant at one of . Data: Kielland et al. (2017)


```{r}
ggplot(data=palmetto, aes(x=green_lvs))+
  geom_histogram(binwidth = 1)+
  facet_wrap(~species)+
  labs( x = "number of green leaves (n)",
        y = "count")
```

```{r}
summary_palmetto <- palmetto %>% 
  group_by(species) %>% 
  summarize(mean = mean(height, na.rm=TRUE),
            sd = sd(height, na.rm=TRUE),
            #median = median(weight, na.rm=TRUE),
            n = n()
            )

ggplot(data=palmetto, aes(x=species, y=height))+
  geom_boxplot()+
  geom_jitter(color="black", size=0.4, alpha=0.2)

```


## Binary logistic equation


```{r}
palmetto_blr <- glm(species ~ height + length + width + green_lvs, 
                            data = palmetto_factor,
                            family = "binomial") #specify model is BLR

palmetto_blr
summary(palmetto_blr)
tidy(palmetto_blr)
```
```{r}
blr_fitted_palmetto <- palmetto_blr %>% 
  broom::augment(type.predict="response") %>% # calculate probability for each outcome
  select(species,.fitted) %>% 
  mutate(classification = case_when( .fitted>0.5 & species=="serenoa repens"~ TRUE,
                                     .fitted<=0.5 & species=="serenoa repens"~ FALSE,
                                     .fitted>0.5 & species=="sabal etonia"~ FALSE,
                                     .fitted<=0.5 & species=="sabal etonia"~ TRUE)) %>% count(species, classification)
```

